config/routes.rb
Rails.application.routes.draw do

  resources :employees
  resources :companies

  # permits to request directly API enpoints w/o validation in development mode
  scope '/debug' do
    resources :employees
    resources :companies
  end if Rails.env.development?

  namespace :explore do
    resources :employees, only: [:index, :show]
    resources :companies, only: [:index, :show]
  end

  root to: 'explore/employees#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :employees

  validates :name, presence: true
  validates :name, uniqueness: true

  def as_json(options={})
    attributes.slice('id', 'name')
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  belongs_to :company

  validates :first_name, :last_name, :company_id, presence: true
  validates :first_name, uniqueness: { scope: :last_name }

  def as_json(options={})
    attributes.slice('id', 'first_name', 'last_name').merge(company: company)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::API
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :update, :destroy]

  include ResulsPagination

  # GET /companies
  def index
    @companies = Company
      .limit(items_per_page)
      .offset(resuls_offset)
    if params[:term].present?
      @companies.where!('name ilike :term', term: "%#{ params[:term] }%")
    end

    render json: @companies
  end

  # GET /companies/1
  def show
    render json: @company
  end

  # POST /companies
  def create
    @company = Company.new(company_params)

    if @company.save
      render json: @company, status: :created, location: @company
    else
      render json: @company.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /companies/1
  def update
    if @company.update(company_params)
      render json: @company
    else
      render json: @company.errors, status: :unprocessable_entity
    end
  end

  # DELETE /companies/1
  def destroy
    @company.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def company_params
      params.require(:company).permit(:name)
    end
end

app/controllers/concerns/resuls_pagination.rb
module ResulsPagination

   private

   def items_per_page
     10
   end

   def resuls_offset
     items_per_page * page_index
   end

   def page_index
     (params[:page] || 1).to_i - 1
   end


end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :update, :destroy]

  include ResulsPagination

  # GET /employees
  def index
    @employees = Employee
    .limit(items_per_page)
    .offset(resuls_offset)

    if params[:term].present?
      @employees.where!('first_name ilike :term OR last_name ilike :term', term: "%#{ params[:term] }%")
    end

    render json: @employees
  end

  # GET /employees/1
  def show
    render json: @employee
  end

  # POST /employees
  def create
    @employee = Employee.new(employee_params)

    if @employee.save
      render json: @employee, status: :created, location: @employee
    else
      render json: @employee.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /employees/1
  def update
    if @employee.update(employee_params)
      render json: @employee
    else
      render json: @employee.errors, status: :unprocessable_entity
    end
  end

  # DELETE /employees/1
  def destroy
    @employee.destroy
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :company_id)
    end
end

app/controllers/explore/base_controller.rb
module Explore
  class BaseController < ActionController::Base

    layout 'base'

  end
end

app/controllers/explore/companies_controller.rb
module Explore
  class CompaniesController < BaseController

    def index
      render layout: true
    end

  end
end

app/controllers/explore/employees_controller.rb
module Explore
  class EmployeesController < BaseController

    def index
      render layout: true
    end

  end
end

app/views/explore/companies/index.html.erb
<div class="container" ref="container" data-api-url="/companies">
  <nav>
    <%= link_to 'Show Employees', explore_employees_path %>
  </nav>
  <h1>Companies</h1>
  <p class="desc">List companies. Page: {{pageNum}}</p>

  <p>
      <button @click="prevPage" class="addItemButton" v-if="pageNum > 1">Previous Page</button>
      <button @click="nextPage"  class="addItemButton" v-if="!noResults">Next Page</button>
  </p>

  <form @submit="searchEmployee">
        <input v-model="term" class="addItemInput" type="search" placeholder="e.g. Siemens"/>
        <button type="submit" class="addItemButton">Search</button>
  </form>

  <ul v-for="item in results" class="list">
    <li>
      <div>{{item.name}}</div>
    </li>
  </ul>

  <div v-if="noResults" class="section">
    Sorry, no results found.
  </div>

  <div v-if="searching" class="section">
    <i>Searching...</i>
  </div>
</div>

app/views/explore/employees/index.html.erb
<div class="container" ref="container" data-api-url="/employees">
  <nav>
    <%= link_to 'Show Companies', explore_companies_path %>
  </nav>
  <h1>Employees</h1>
  <p class="desc">List employees. Page: {{pageNum}}</p>

  <p>
      <button @click="prevPage" class="addItemButton" v-if="pageNum > 1">Previous Page</button>
      <button @click="nextPage"  class="addItemButton" v-if="!noResults">Next Page</button>
  </p>

  <form @submit="searchEmployee">
        <input v-model="term" class="addItemInput" type="search" placeholder="e.g. John"/>
        <button type="submit" class="addItemButton">Search</button>
  </form>

  <ul v-for="item in results" class="list">
    <li>
      <div class="person">{{item.first_name | capitalize }} {{item.last_name | capitalize}}</div>
      <div class="company">{{item.company.name}}</div>
    </li>
  </ul>

  <div v-if="noResults" class="section">
    Sorry, no results found.
  </div>

  <div v-if="searching" class="section">
    <i>Searching...</i>
  </div>
</div>

app/views/layouts/base.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8">
		<title></title>
		<meta name="viewport" content="width=device-width">

		<style>
			[v-cloak] {display: none}
		</style>

    <link rel="stylesheet" href="/style.css">
	</head>
	<body>
			<div id="app" v-cloak>
        <%= yield %>
			</div>

		<script src="https://unpkg.com/vue"></script>
		<script src="/app.js"></script>

	</body>
</html>